jobs:
  configure:
    steps:
    - name: Configure puppet server
      run: |
        echo "[main]" | sudo tee -a /etc/puppetlabs/puppet/puppet.conf > /dev/null
        echo "server = "$HOSTNAME | sudo tee -a /etc/puppetlabs/puppet/puppet.conf > /dev/null
        echo "dns_alt_names = "$HOSTNAME | sudo tee -a /etc/puppetlabs/puppet/puppet.conf > /dev/null
        sudo echo "127.0.0.1 puppet" | sudo tee -a /etc/hosts > /dev/null
        sudo cat /etc/puppetlabs/puppet/puppet.conf

    - name: Start Puppet Server
      run: |
        sudo systemctl start puppetserver
        sudo systemctl enable puppetserver
        sudo systemctl status puppetserver