
name: kitchen

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest

    container: jm404:wazuh-puppet

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Running converge
      run: "kitchen converge


#name: kitchen
#
#on: [push]
#
#jobs:
#  dokken:
#
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        os: ['debian-8']
#        suite: ['default']
#      fail-fast: false
#
#    steps:
#    - name: Check out code
#      uses: actions/checkout@v2
#    - name: Dokken
#      uses: './.github/actions/test_manager_and_agent'
#
##jobs:
##  build:
##    name: Linting Verifier
##    runs-on: ubuntu-latest
##    steps:
##    - name: Clone repository
##      uses: actions/checkout@v2
##
##    - name: Build and launch Linting test
##      uses: './.github/actions/validate_module'
#
#
#
#