name: Verify Linting

on: [push]

jobs:
  build:
    name: Linting Verifier
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Build and launch Linting test
      uses: 'wazuh/puppet-validate@0.0.1'
