name: Kitchen tests for Wazuh Puppet

on: [push, workflow_dispatch]

jobs:

  ubuntu16:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Ubuntu 16.04 - (Manager + Agent)
        uses: './.github/actions/test_manager_and_agent'
        env:
          IMAGE: jrei/systemd-ubuntu:16.04
          PLATFORM: ubuntu
          RELEASE: 16
          RUN_COMMAND: /sbin/init
