name: Kitchen tests for Wazuh Puppet

on: [push, pull_request]

jobs:

  validate-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - name: Create enviroment variables
      run: |
        cat VERSION > $GITHUB_ENV

    - name: Install Puppet
      uses: ./.github/debian_install

    - name: Download and Install pdk
      run: |
        wget https://apt.puppet.com/puppet-tools-release-focal.deb
        sudo dpkg -i puppet-tools-release-focal.deb
        sudo apt-get update
        sudo apt-get install pdk

    - name: Create Puppet module
      run: |
        pdk validate
        pdk build

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: wazuh-module
        path: ./pkg/wazuh-wazuh-${{ env.VERSION }}.tar.gz
#-------------------------------------------------------------------------------
  ubuntu20:
    runs-on: ubuntu-20.04
    needs: validate-and-build
    steps:
    - uses: actions/checkout@v2

    - name: Create enviroment variables
      run: |
        cat VERSION > $GITHUB_ENV

    - name: Install Puppet
      uses: ./.github/debian_install

    - name: Configure Puppet server
      uses: ./.github/configure

    - name: Retrieve saved Wazuh module
      uses: actions/download-artifact@v3
      with:
        name: wazuh-module

    - name: Install Wazuh Module
      run: |
        sudo puppet module install ./wazuh-wazuh-${{ env.VERSION }}.tar.gz

    - name: Install Wazuh Stack
      uses: ./.github/install_stack

    - name: Test stack
      uses: ./.github/tests
#-------------------------------------------------------------------------------
  ubuntu22:
    runs-on: ubuntu-22.04
    needs: validate-and-build
    steps:
    - uses: actions/checkout@v2

    - name: Create enviroment variables
      run: |
        cat VERSION > $GITHUB_ENV

    - name: Install Puppet
      uses: ./.github/debian_install

    - name: Configure Puppet server
      uses: ./.github/configure

    - name: Retrieve saved Wazuh module
      uses: actions/download-artifact@v3
      with:
        name: wazuh-module

    - name: Install Wazuh Module
      run: |
        sudo puppet module install ./wazuh-wazuh-${{ env.VERSION }}.tar.gz

    - name: Install Wazuh Stack
      uses: ./.github/install_stack

    - name: Test stack
      uses: ./.github/tests

#-------------------------------------------------------------------------------
  Centos7:
    runs-on: ubuntu-22.04
    needs: validate-and-build
    steps:
    - uses: actions/checkout@v2

    - name: Create enviroment variables
      run: |
        cat VERSION > $GITHUB_ENV
        echo $GITHUB_ENV > /tmp/.env
        cat

    - name: Retrieve saved Wazuh module
      uses: actions/download-artifact@v3
      with:
        name: wazuh-module

    - name: Move Wazuh Module
      run: |
        mv ./wazuh-wazuh-${{ env.VERSION }}.tar.gz /tmp/
        cp ./.github/scripts/centos_install.sh /tmp/

    - name: Initiate Docker image for Centos
      run: |
        docker run -i -v /tmp/wazuh-wazuh-${{ env.VERSION }}.tar.gz:/tmp/wazuh-wazuh-${{ env.VERSION }}.tar.gz -v /tmp/centos_install.sh:/tmp/install.sh -e VERSION --privileged --cgroupns_mode=host -v /sys/fs/cgroup:/sys/fs/cgroup:rw  wazuh/centos7_systemd:latest bash /tmp/install.sh

    - name: Test stack
      uses: ./.github/tests