
name: kitchen

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Ubuntu 18.04 - (Manager + Agent)
      uses: './.github/actions/test_manager_and_agent'
      env:
        IMAGE: jrei/systemd-ubuntu:18.04
        PLATFORM: ubuntu
        RELEASE: 18
        RUN_COMMAND: /sbin/init
