name: Kitchen tests for Wazuh Puppet

on: [push, pull_request]

jobs:

  validate-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create enviroment variables
      run: |
        cat VERSION > $GITHUB_ENV

    - name: Install Puppet
      uses: ./.github/jobs/debian.yml

    - name: Download and Install pdk
      run: |
        wget https://apt.puppet.com/puppet-tools-release-focal.deb
        sudo dpkg -i puppet-tools-release-focal.deb
        sudo apt-get update
        sudo apt-get install pdk

    - name: Create Puppet module
      run: |
        pdk update
        pdk validate
        pdk build

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: wazuh-module
        path: ./pkg/wazuh-wazuh-${{ env.VERSION }}.tar.gz
#-------------------------------------------------------------------------------
  ubuntu20:
    runs-on: ubuntu-20.04
    needs: validate-and-build
    steps:
    - uses: actions/checkout@v2

    - name: Create enviroment variables
      run: |
        cat VERSION > $GITHUB_ENV

    - name: Install Puppet
      uses: ./.github/jobs/debian.yml

    - name: Configure Puppet server
      uses: ./.github/jobs/configure.yml

    - name: Retrieve saved Wazuh module
      uses: actions/download-artifact@v3
      with:
        name: wazuh-module

    - name: Install Wazuh Module
      run: |
        sudo puppet module install ./wazuh-wazuh-${{ env.VERSION }}.tar.gz

    - name: Install Wazuh Stack
      uses: ./.github/jobs/install_stack.yml

    - name: Test stack
      uses: ./.github/jobs/tests.yml
#-------------------------------------------------------------------------------
  ubuntu22:
    runs-on: ubuntu-22.04
    needs: validate-and-build
    steps:
    - uses: actions/checkout@v2

    - name: Create enviroment variables
      run: |
        cat VERSION > $GITHUB_ENV

    - name: Install Puppet
      uses: ./.github/jobs/debian.yml

    - name: Configure Puppet server
      uses: ./.github/jobs/configure.yml

    - name: Retrieve saved Wazuh module
      uses: actions/download-artifact@v3
      with:
        name: wazuh-module

    - name: Install Wazuh Module
      run: |
        sudo puppet module install ./wazuh-wazuh-${{ env.VERSION }}.tar.gz

    - name: Install Wazuh Stack
      uses: ./.github/jobs/install_stack.yml

    - name: Test stack
      uses: ./.github/jobs/tests.yml